package Vista;

import javax.swing.table.DefaultTableModel;
import Modelo.*;
import Persistencia.*;
import java.sql.Connection;
import java.util.ArrayList;


public class ListarInscripciones extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloLI = new DefaultTableModel();
    private ArrayList<Materia> listaMateria;
    private ArrayList<Alumno> listaAlumno;
    private InscripcionData inscData;
    private MateriaData mData;
    private AlumnoData aData;
    Connection con = null;
    
    
    public ListarInscripciones() {
        initComponents();
        aData = new AlumnoData();
        mData = new MateriaData();
        inscData = new InscripcionData();
        listaAlumno = (ArrayList<Alumno>)aData.listarAlumnos();
        listaMateria = (ArrayList<Materia>)mData.listarMaterias();
        modeloLI = new DefaultTableModel();
        cargarMaterias();
       
        armarCabecera();
    }

    private void cargarMaterias(){
        for(Materia materia: listaMateria){       
            jcb_Materia.addItem(materia);
        }
    }
    
 
    
    private void borrarFilaTabla(){
        int indice = modeloLI.getRowCount() -1;
        for(int i = indice;i >= 0; i--){
            modeloLI.removeRow(i);
        }
    }
   
    private void alumnosInscriptos(){
        borrarFilaTabla();
        Materia select = (Materia)jcb_Materia.getSelectedItem();
        listaAlumno = (ArrayList)inscData.obtenerAlumnosMateria(select.getId_materia());
        for(Alumno alumno: listaAlumno){    
            modeloLI.addRow(new Object[] {
                alumno.getId_alumno(),
                alumno.getNombre(),
                alumno.getApellido()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        lbl_seleccion = new javax.swing.JLabel();
        jcb_Materia = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_lista_inscripciones = new javax.swing.JTable();

        setClosable(true);

        lbl_titulo.setText("Lista de Inscripciones");

        lbl_seleccion.setText("Seleccione Materia :");

        jcb_Materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_MateriaActionPerformed(evt);
            }
        });

        tbl_lista_inscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_lista_inscripciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lbl_seleccion)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(lbl_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_seleccion)
                    .addComponent(jcb_Materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_MateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_MateriaActionPerformed
    alumnosInscriptos();  
    }//GEN-LAST:event_jcb_MateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Materia> jcb_Materia;
    private javax.swing.JLabel lbl_seleccion;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTable tbl_lista_inscripciones;
    // End of variables declaration//GEN-END:variables
private void armarCabecera() {
        modeloLI.addColumn("ID");
        modeloLI.addColumn("Nombre");
        modeloLI.addColumn("Apellido");
        tbl_lista_inscripciones.setModel(modeloLI);
    }
}
