/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author abate
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_alumnos = new javax.swing.JMenu();
        mit_alumno = new javax.swing.JMenuItem();
        menu_materias = new javax.swing.JMenu();
        mit_materia = new javax.swing.JMenuItem();
        menu_inscripcion = new javax.swing.JMenu();
        mit_inscripcion = new javax.swing.JMenuItem();
        mit_notas = new javax.swing.JMenuItem();
        mit_inscriptos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );

        menu_alumnos.setText("Alumno");

        mit_alumno.setText("Gestion Alumno");
        mit_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_alumnoActionPerformed(evt);
            }
        });
        menu_alumnos.add(mit_alumno);

        jMenuBar1.add(menu_alumnos);

        menu_materias.setText("Materia");

        mit_materia.setText("Gestion Materia");
        mit_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_materiaActionPerformed(evt);
            }
        });
        menu_materias.add(mit_materia);

        jMenuBar1.add(menu_materias);

        menu_inscripcion.setText("Inscripcion");

        mit_inscripcion.setText("Gestion Inscripcion");
        mit_inscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_inscripcionActionPerformed(evt);
            }
        });
        menu_inscripcion.add(mit_inscripcion);

        mit_notas.setText("Cargar Notas");
        mit_notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_notasActionPerformed(evt);
            }
        });
        menu_inscripcion.add(mit_notas);

        mit_inscriptos.setText("Listar Inscriptos");
        mit_inscriptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_inscriptosActionPerformed(evt);
            }
        });
        menu_inscripcion.add(mit_inscriptos);

        jMenuBar1.add(menu_inscripcion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mit_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_alumnoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaAlumnos vistaAlumnos = new VistaAlumnos();
        vistaAlumnos.setVisible(true);
        escritorio.add(vistaAlumnos);
        escritorio.moveToFront(vistaAlumnos);
    }//GEN-LAST:event_mit_alumnoActionPerformed

    private void mit_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_materiaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaMaterias vistaMaterias = new VistaMaterias();
        vistaMaterias.setVisible(true);
        escritorio.add(vistaMaterias);
        escritorio.moveToFront(vistaMaterias);
    }//GEN-LAST:event_mit_materiaActionPerformed

    private void mit_inscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_inscripcionActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaInscripcion vistaInscripcion = new VistaInscripcion();
        vistaInscripcion.setVisible(true);
        escritorio.add(vistaInscripcion);
        escritorio.moveToFront(vistaInscripcion);
    }//GEN-LAST:event_mit_inscripcionActionPerformed

    private void mit_notasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_notasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaCargarNotas vistaCargarNotas = new VistaCargarNotas();
        vistaCargarNotas.setVisible(true);
        escritorio.add(vistaCargarNotas);
        escritorio.moveToFront(vistaCargarNotas);
    }//GEN-LAST:event_mit_notasActionPerformed

    private void mit_inscriptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_inscriptosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ListarInscripciones listarInscripciones = new ListarInscripciones();
        listarInscripciones.setVisible(true);
        escritorio.add(listarInscripciones);
        escritorio.moveToFront(listarInscripciones);
    }//GEN-LAST:event_mit_inscriptosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_alumnos;
    private javax.swing.JMenu menu_inscripcion;
    private javax.swing.JMenu menu_materias;
    private javax.swing.JMenuItem mit_alumno;
    private javax.swing.JMenuItem mit_inscripcion;
    private javax.swing.JMenuItem mit_inscriptos;
    private javax.swing.JMenuItem mit_materia;
    private javax.swing.JMenuItem mit_notas;
    // End of variables declaration//GEN-END:variables
}
